### ISSUE TITLE
PiTFT Install script not at all friendly to use within other scripts

### ISSUE THREAD

**Issue by kevinkahn** [adafruit/Raspberry-Pi-Installer-Scripts#101] opened 2020-07-24 16:59 UTC
I have a program I support for Home Automation that recommends using PiTFTs as its console.  That program has an overall install script that wants to make it easy for the user so it handles invoking the pitft install script that you provide.  Unfortunately, your script really does not contemplate such use.  If it did it would provide a command line alternative to interaction.  However, since it is what you provide I handle creating a response file for the interactive questions that I use as input to the script.  This is very fragile as I was again reminded when you recently changed to add a new screen type and order of the possible screens changed, as did the number I needed to input.  As a result a user of mine wound up with the wrong screen type installed on his system.  It really wouldn't be hard (and it would certainly be good software practice) to provide a stable interface to this script that progamatic callers could rely on.

**Comment by ladyada** [comment] 2020-07-24 17:25
closing as duplicate of https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/issues/13

**Closed by ladyada** 2020-07-24 17:25 UTC
