### ISSUE TITLE
Pi TFT HDMI mirror option not working

### ISSUE THREAD

**Issue by caternuson** [adafruit/Raspberry-Pi-Installer-Scripts#186] opened 2021-08-23 15:53 UTC
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=50&t=182420

**Comment by makermelissa** [comment] 2021-09-09 18:38
Ok, I was able to reproduce the issue. If HDMI is plugged in, the display doesn't show anything and the monitor shows 2 screens in odd colors at the PiTFT's resolution. If no HDMI is plugged in, the TFT displays normal.

**Comment by makermelissa** [comment] 2021-09-09 19:13
Ok good news. Plugging my HDMI monitor into the other port and rebooting a couple of times seems to be working.

**Comment by makermelissa** [comment] 2021-09-09 20:48
Closing because no code changes were required. Using the HDMI port next to the display fixes the issue. I replied in the forums.

**Closed by makermelissa** 2021-09-09 20:48 UTC
