### ISSUE TITLE
Error when I try install https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/master/libgpiod.sh

### ISSUE THREAD

**Issue by juanCGVE** [adafruit/Raspberry-Pi-Installer-Scripts#184] opened 2021-08-12 07:27 UTC
I run the bash file and show me this error:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
aclocal: couldn't open directory `m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
cp: cannot stat 'bindings/python/.libs/gpiod.so': No such file or directory
cp: cannot stat 'bindings/python/.libs/gpiod.la': No such file or directory
cp: cannot stat 'bindings/python/.libs/gpiod.a': No such file or directory

Do you know how I can solve it?
thanks in advance

**Comment by makermelissa** [comment] 2021-08-12 17:29
Duplicate of #183

**Closed by makermelissa** 2021-08-12 17:29 UTC
